
#+TITLE: My DOOM EMACS setup guide
#+DESCRIPTION: A guide to installing and configuring EMACS with the DOOM configuration
#+AUTHOR: Shawn Gerrard <shawn.gerrard@gmail.com>

* DOOM EMACS setup
A guide to installing and configuring my DOOM EMACS setup.

* Pre-requisites :prereqs:
You need to ensure the following dependencies are installed to follow this guide successfully.

- Ubuntu LTS (currently 22.04+)

  #+begin_quote
*Note*: It's recommended that you follow my [[https://github.com/shawngerrard/ubuntu-tooling][guide to installing and configuring Ubuntu]].
  #+end_quote

- Git 2.23+
- [[Https://github.com/BurntSushi/ripgrep][ripgrep]] (11.01)
- (Optional) [[https://github.com/sharkdp/fd][fd]]

* Installing EMACS :installingemacs:

The first step is to install the base vanilla Gnu-EMACS application compatible with DOOM. For the purposes of this guide, we'll be installing *Gnu-EMACS version 28.1*. At this point in time, the minimum required EMACS version is 27.1.

#+begin_quote
*Note*: You'll need to review the [[https://github.com/doomemacs/doomemacs#prerequisites][DOOM prerequisites for EMACS]] to identify the EMACS versions compatible with DOOM.
#+end_quote

** Installing EMACS using the Ubuntu apt package manager :apt:

To get up and running quickly, you can install ~emacs~ using the ~apt~ package manager.

#+begin_src bash
sudo apt install emacs
#+end_src

To uninstall ~emacs~ you'll need to also remove all dependencies.

#+begin_src bash
sudo apt-get remove emacs emacs23 emacs24 emacs25 emacs26 emacs-bin-common emacs-common emacs-el
#+end_src

** (Recommended) Installing EMACS by building from source :source:

You'll need the following packages installed to be able to build the ~emacs~ source.

#+begin_src bash
libcurses-dev libgnutls28-dev gnutls-bin pkg-config
#+end_src

Then, obtain the source code tarball for the specific version you want. In this case, we're installing version 28.1.

#+begin_src bash
wget https://ftp.gnu.org/gnu/emacs/emacs-28.1.tar.xz
#+end_src

Extract the source code from the tarball.

#+begin_src bash
tar xvf emacs-28.1.tar.xz
#+end_src

Finally, configure, build, and install ~emacs~ using the scipts supplied with the source files.

#+begin_src bash
cd emacs-28.1
./configure
make
make install
#+end_src

You should now be able to start ~emacs~ successfully.

* Installing DOOM :installingdoom:

Run the following command to clone the DOOM configuration to your local computer:

#+begin_src bash
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

Add the DOOM binary files to the ~PATH~ environment variable. You'll need to add the following line to the bottom of your ~~/.bashrc~ configuration file:

#+begin_src bash
export PATH="~/.config/emacs/bin:$PATH"
#+end_src

#+begin_quote
*Note*: Delete the `~/.emacs.d` folder if this exists - `emacs` will initially look in there for configuration files.
#+end_quote

If you have any private ~emacs~ configuration to sync with DOOM, or if you've made changes to ~init.el~ or ~packages.el~, you'll need to run ~doom sync~.

Finally, to run the new setup, start up ~emacs~ normally in the terminal. You should be met with the DOOM landing screen.

#+begin_quote
*Note*: Visit [[https://github.com/doomemacs/doomemacs][the official DOOM GitHub repository]] for more information if you have any installation issues.
#+end_quote
