
#+TITLE: My DOOM EMACS setup guide
#+DESCRIPTION: A guide to installing and configuring EMACS with the DOOM configuration
#+AUTHOR: Shawn Gerrard <shawn.gerrard@gmail.com>

* DOOM EMACS setup
A guide to installing and configuring my DOOM EMACS setup.

* Pre-requisites :prereqs:
You need to ensure the following dependencies are installed to follow this guide successfully.

- Ubuntu LTS (currently 22.04+)

  #+begin_quote
*Note*: It's recommended that you follow my [[https://github.com/shawngerrard/ubuntu-tooling][guide to installing and configuring Ubuntu]].
  #+end_quote

- Git 2.23+
- [[Https://github.com/BurntSushi/ripgrep][ripgrep]] (11.01)
- (Optional) [[https://github.com/sharkdp/fd][fd]]

* Installing EMACS :installingemacs:

The first step is to install the base vanilla Gnu-EMACS application compatible with DOOM. For the purposes of this guide, we'll be installing *Gnu-EMACS version 28.1*. At this point in time, the minimum required EMACS version is 27.1.

#+begin_quote
*Note*: You'll need to review the [[https://github.com/doomemacs/doomemacs#prerequisites][DOOM prerequisites for EMACS]] to identify the EMACS versions compatible with DOOM.
#+end_quote

** Installing EMACS using the Ubuntu apt package manager :apt:

To get up and running quickly, you can install ~emacs~ using the ~apt~ package manager.

#+begin_src bash
sudo apt install emacs28
#+end_src

To uninstall ~emacs~ you'll need to also remove all dependencies.

#+begin_src bash
sudo apt-get remove emacs emacs28 emacs-bin-common emacs-common emacs-el
#+end_src

** (Recommended) Installing EMACS by building from source :sourcecode:

You'll need the following packages installed to build the ~emacs~ source.

#+begin_src bash
libcurses-dev libgnutls28-dev gnutls-bin pkg-config
#+end_src

Then, obtain the source code tarball for the specific version you want. In this case, we're installing version 28.1.

#+begin_src bash
wget https://ftp.gnu.org/gnu/emacs/emacs-28.1.tar.xz
#+end_src

Extract the source code from the tarball.

#+begin_src bash
tar xvf emacs-28.1.tar.xz
#+end_src

Finally, configure, build, and install ~emacs~ using the scipts supplied with the source files.

#+begin_src bash
cd emacs-28.1
./configure
sudo make
sudo make install
#+end_src

You should now be able to start ~emacs~ successfully.

To uninstall ~emacs~ you can follow the steps above but instead of ~sudo make install~ you can run ~sudo make uninstall~

* Apply the DOOM configuration to EMACS

You can find information on the DOOM configuration framework for ~emacs~ in the [[https://github.com/doomemacs/doomemacs#introduction][DOOMEMACS github repository]].

It's recommended that you ensure your system is up-to-date.

#+begin_src bash
sudo apt update && sudo apt upgrade
#+end_src

Now, we clone the DOOM configuration from git into the ~$HOME/emacs.d~ directory, and use the ~doom install~ function from the binary.

#+begin_src bash
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src

#+begin_quote
*Note*: Ensure that you have an SSH authentication key-pair loaded into git and the local ssh-agent. You may need to add this code to your ~bashrc~ configuration.
#+end_quote

You should be able to run ~doom doctor~ to diagnose any problems associated with an installation or with the system configuration.

The next time you open ~emacs~, your DOOM configuration should be loaded.
