
#+TITLE: My DOOM EMACS setup guide
#+DESCRIPTION: A guide to installing and configuring EMACS with the DOOM configuration
#+AUTHOR: Shawn Gerrard <shawn.gerrard@gmail.com>

* DOOM EMACS setup
A guide to installing and configuring my DOOM EMACS setup.

* Pre-requisites :prereqs:
You need to ensure the following dependencies are installed to follow this guide successfully.

- Ubuntu LTS (currently 22.04+)

  #+begin_quote
*Note*: It's recommended that you follow my [[https://github.com/shawngerrard/ubuntu-tooling][guide to installing and configuring Ubuntu]].
  #+end_quote

- Git 2.23+
- [[Https://github.com/BurntSushi/ripgrep][ripgrep]] (11.01)
- (Optional) [[https://github.com/sharkdp/fd][fd]]

* Installing EMACS :installingemacs:

The first step is to install the base vanilla Gnu-EMACS application compatible with DOOM. For the purposes of this guide, we'll be installing *Gnu-EMACS version 28.1*. At this point in time, the minimum required EMACS version is 27.1.

#+begin_quote
*Note*: You'll need to review the [[https://github.com/doomemacs/doomemacs#prerequisites][DOOM prerequisites for EMACS]] to identify the EMACS versions compatible with DOOM.
#+end_quote

** Installing EMACS using the Ubuntu apt package manager :apt:

To get up and running quickly, you can install ~emacs~ using the ~apt~ package manager.

#+begin_src bash
sudo apt install emacs28
#+end_src

To uninstall ~emacs~ you'll need to also remove all dependencies.

#+begin_src bash
sudo apt-get remove emacs emacs28 emacs-bin-common emacs-common emacs-el
#+end_src

** (Recommended) Installing EMACS by building from source :source:

You'll need the following packages installed to build the ~emacs~ source.

#+begin_src bash
libcurses-dev libgnutls28-dev gnutls-bin pkg-config
#+end_src

Then, obtain the source code tarball for the specific version you want. In this case, we're installing version 28.1.

#+begin_src bash
wget https://ftp.gnu.org/gnu/emacs/emacs-28.1.tar.xz
#+end_src

Extract the source code from the tarball.

#+begin_src bash
tar xvf emacs-28.1.tar.xz
#+end_src

Finally, configure, build, and install ~emacs~ using the scipts supplied with the source files.

#+begin_src bash
cd emacs-28.1
./configure
sudo make
sudo make install
#+end_src

You should now be able to start ~emacs~ successfully.

> *Note*: To uninstall ~emacs~ you can follow the step above but instead of ~sudo make install~ you can run ~sudo make uninstall~

* Installing DOOM :installingdoom:

Run the following command to clone the DOOM configuration to your local computer:

#+begin_src bash
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

Add the DOOM binary files to the ~PATH~ environment variable. You'll need to add the following line to the bottom of your ~​~/.bashrc~ configuration file:

#+begin_src bash
export PATH="~/.config/emacs/bin:$PATH"
#+end_src

#+begin_quote
*Note*: Delete the ~​~/.emacs.d~ folder if this exists - ~emacs~ will initially look in there for configuration files.
#+end_quote

If you have any private ~emacs~ configuration to sync with DOOM, or if you've made changes to ~init.el~ or ~packages.el~, you'll need to run ~doom sync~.

Finally, to run the new setup, start up ~emacs~ normally in the terminal. You should be met with the DOOM landing screen.

#+begin_quote
*Note*: Visit [[https://github.com/doomemacs/doomemacs][the official DOOM GitHub repository]] for more information if you have any installation issues.
#+end_quote

* Alternative - Install DOOM and apply configuration to EMACS

You can find information on the DOOM configuration framework for ~emacs~ in the [[https://github.com/doomemacs/doomemacs#introduction][DOOMEMACS github repository]].

It's recommended that you ensure your system is up-to-date.

#+begin_src bash
sudo apt update && sudo apt upgrade
#+end_src

Now, we clone the DOOM configuration from git into the ~$HOME/emacs.d~ directory, and use the ~doom install~ function from the binary.

#+begin_src bash
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src

#+begin_quote
*Note*: Ensure that you have an SSH authentication key-pair loaded into git and the local ssh-agent. You may need to add this code to your ~bashrc~ configuration.
#+end_quote

You should be able to run ~doom doctor~ to diagnose any problems associated with an installation or with the system configuration.

The next time you open ~emacs~, your DOOM configuration should be loaded.

* Customizations

I've made a number of customizations to EMACS that are helpful.

** Org-Agenda

I've made an update to ~​~/.config/doom/init.el~ to change the directory that ~org-agenda~ uses to find TODO items (~​~/documents/*~).

At the bottom of the ~init.el~ file, I've inserted the following code:
#+begin_src elisp
(setq org-agenda-files (directory-files-recursively "~/documents/" "\\.org$"))
#+end_src

Restart DOOMEMACS to apply changes. When prompted, select ~n~ to avoid importing variables from other org files outside of this directory.

* Useful keybinds

By default, I run DOOMEMACS in ~evil~ mode, which means that keybinds in EMACS emulate ~vi/vim~ keybinds.

** Legend for US Keyboard layout

- ~M-~ is short for "Meta key" and is bound to ~ALT~
- ~C-~ is short for "Control key" and is bound to ~CTRL~
- ~S-~ is short for "Super key" and is bound to ~SHIFT~
- ~SPC-~ is known as a "Leader" key:
  - *In evil-mode* this is bound to ~SPC~.

  #+begin_quote
*Note*: You must change to evil-mode to use the leader key in DOOMEMACS.
  #+end_quote

** Keybinds

*** Disable evil-mode

*Rationale*: Some of the descriptions in documentation (such as ~SPC-h~ or ~M-x~) for DOOMEMACS are intended for SPACEMACS users rather than ~vi/vim~ users, which can be confusing as simple keybinds for /killing/yanking/ etc are different from what is stated.

Easiest way to disable evil-mode is to toggle is with: ~M-x evil-mode~

#+begin_quote
*Note*: This will only toggle evil-mode for the current EMACS session. To disable evil-mode permanently, refer to the StackExchange forum post: [[https://emacs.stackexchange.com/questions/53319/how-to-disable-evil-mode-everywhere][https://emacs.stackexchange.com/questions/53319/how-to-disable-evil-mode-everywhere]]
#+end_quote

*** Insert a link snippet (E.G - a URL)

Insert a URL with ~C-c C-l~ and paste in the URL.

*** Kill/yank commands

I prefer using the ~mark~ functionality to select text. You can set a mark by using ~C-SPC~, then use your left/right keys to highlight the text you want to manipulate.

Then, press any of the operations as per below to operate over the text accordingly.

***** Evil mode

- Copy: ~y~
- Cut: ~d~
- Paste: ~P~ or ~S-p~

***** Default mode

- Copy: ~M-w~
- Cut: ~C-w~
- Paste: ~C-y~

*** Insert an escape character

*Rationale*: When inserting a file path into the start of a code block, such as ~​~/documents/~, this can create formatting issues when the org file is rendered, requiring us to place an escape character beside the initial tilde.

Insert a ~zero width space~ beside the first tilde with ~C-x 8 <RET> zero width space <RET>~.
